from fastapi import BackgroundTasks, FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates

import json
import os
import platform
import re
import threading
import time
import uuid
from datetime import datetime

import psutil
import requests

from app.rag import retrieve_context
from app.orchestrator import orchestrate_request
from app.docker_monitor import get_docker_metrics
from app.telemetry_history import record_telemetry, get_history
from app.sourcegraph import search_sourcegraph, sourcegraph_status


# ============================================================
# DEVPULSE NEXUS
# AI-Powered Developer Environment Observability
# and AIDevOps Intelligence
# ============================================================

app = FastAPI(
    title="DevPulse Nexus",
    description=(
        "AI-powered developer environment observability, "
        "Digital Twin telemetry, Docker monitoring, and "
        "RAG-based troubleshooting."
    ),
    version="1.0.0",
)

templates = Jinja2Templates(directory="templates")


# ============================================================
# CONFIGURATION
# ============================================================

# IMPORTANT:
# Inside Docker, Ollama is reached through the Compose service
# name "ollama", not 127.0.0.1.
OLLAMA_BASE_URL = os.getenv(
    "OLLAMA_URL",
    "http://ollama:11434",
).rstrip("/")

OLLAMA_URL = f"{OLLAMA_BASE_URL}/api/generate"

OLLAMA_MODEL = os.getenv(
    "OLLAMA_MODEL",
    "qwen2.5:1.5b",
)

# Keep generation moderate because the model is running locally.
OLLAMA_NUM_PREDICT = 160

# Number of RAG documents to retrieve.
RAG_RESULTS = 2

# Maximum time allowed for Ollama to respond.
OLLAMA_TIMEOUT = 120

# A single container must consume a meaningful share of the Docker/WSL memory
# budget before it is reported as a possible host-memory contributor. Docker's
# ``MemPerc`` measures usage against a *container limit*, which can be as small
# as 50 MiB; it must not be treated as a percentage of host memory.
SIGNIFICANT_HOST_MEMORY_SHARE_PERCENT = 5.0


# ============================================================
# UTILITY
# ============================================================

def now_iso():
    """Return the current local timestamp."""
    return datetime.now().isoformat()


# ============================================================
# SYSTEM TELEMETRY
# ============================================================

def get_system_telemetry():
    """
    Collect live host-level telemetry.

    This is observational data.
    It is not generated by the AI model.
    """

    memory = psutil.virtual_memory()
    disk = psutil.disk_usage("/")

    return {
        "platform": platform.system(),
        "kernel": platform.release(),

        "cpu": {
            "usage_percent": psutil.cpu_percent(interval=0.3),
            "cores": psutil.cpu_count() or 0,
        },

        "memory": {
            "total_gb": round(
                memory.total / (1024 ** 3),
                2,
            ),
            "used_gb": round(
                memory.used / (1024 ** 3),
                2,
            ),
            "available_gb": round(
                memory.available / (1024 ** 3),
                2,
            ),
            "usage_percent": memory.percent,
        },

        "disk": {
            "total_gb": round(
                disk.total / (1024 ** 3),
                2,
            ),
            "used_gb": round(
                disk.used / (1024 ** 3),
                2,
            ),
            "free_gb": round(
                disk.free / (1024 ** 3),
                2,
            ),
            "usage_percent": disk.percent,
        },
    }


# ============================================================
# DIGITAL TWIN
# ============================================================

def get_digital_twin():
    """
    Build a point-in-time representation of the
    developer environment.

    The Digital Twin combines:

    - host telemetry
    - Docker telemetry
    """

    return {
        "timestamp": now_iso(),
        "system": get_system_telemetry(),
        "docker": get_docker_metrics(),
    }


# ============================================================
# MEMORY PARSING
# ============================================================

def parse_memory_percentage(value):
    """
    Convert Docker memory percentage strings such as:

        '0.26%'

    into a float.

    Invalid values safely become 0.0.
    """

    if value is None:
        return 0.0

    try:
        return float(
            str(value)
            .replace("%", "")
            .strip()
        )

    except (ValueError, TypeError):
        return 0.0


def parse_memory_usage_bytes(value):
    """Read the used side of Docker's ``used / limit`` memory display."""
    match = re.match(
        r"\s*([0-9]+(?:\.[0-9]+)?)\s*([kmgtpe]?i?b|b)",
        str(value or ""),
        flags=re.IGNORECASE,
    )
    if not match:
        return 0

    amount = float(match.group(1))
    unit = match.group(2).lower()
    multipliers = {
        "b": 1,
        "kb": 1000,
        "mb": 1000 ** 2,
        "gb": 1000 ** 3,
        "tb": 1000 ** 4,
        "pb": 1000 ** 5,
        "eb": 1000 ** 6,
        "kib": 1024,
        "mib": 1024 ** 2,
        "gib": 1024 ** 3,
        "tib": 1024 ** 4,
        "pib": 1024 ** 5,
        "eib": 1024 ** 6,
    }
    return int(amount * multipliers.get(unit, 1))


# ============================================================
# DETERMINISTIC DIAGNOSIS
# ============================================================

def build_diagnosis(digital_twin):
    """
    Produce a deterministic diagnosis from telemetry.

    IMPORTANT:

    This function runs BEFORE the LLM.

    The LLM explains the diagnosis.
    The LLM does not determine the diagnosis.
    """

    system = digital_twin.get("system", {})
    memory = system.get("memory", {})
    docker = digital_twin.get("docker", {})

    host_memory_usage = memory.get(
        "usage_percent",
        0,
    )

    # --------------------------------------------------------
    # Docker unavailable
    # --------------------------------------------------------

    if not docker.get("available", False):

        return {
            "docker_status": "unavailable",
            "running_containers": None,
            "docker_container_memory": "unknown",
            "host_memory_usage_percent": host_memory_usage,
            "docker_is_evidently_responsible": "unknown",
            "assessment": "unknown",
            "significant_containers": [],
            "reason": (
                "Docker telemetry is unavailable. "
                "Docker container memory usage cannot "
                "currently be evaluated."
            ),
        }

    # --------------------------------------------------------
    # Docker available
    # --------------------------------------------------------

    containers = docker.get(
        "containers",
        [],
    )

    container_count = docker.get(
        "container_count",
        len(containers),
    )

    # --------------------------------------------------------
    # No containers
    # --------------------------------------------------------

    if container_count == 0:

        return {
            "docker_status": "available",
            "running_containers": 0,
            "docker_container_memory": "none",
            "host_memory_usage_percent": host_memory_usage,
            "docker_is_evidently_responsible": False,
            "assessment": "not_responsible",
            "significant_containers": [],
            "reason": (
                "No Docker containers are currently "
                "running, so the current host memory "
                "usage cannot be attributed to running "
                "Docker containers."
            ),
        }

    # --------------------------------------------------------
    # Containers exist
    # --------------------------------------------------------

    container_memory = []
    significant_containers = []
    host_memory_total_bytes = int(float(memory.get("total_gb", 0) or 0) * (1024 ** 3))
    total_container_memory_bytes = 0

    for container in containers:

        name = container.get(
            "name",
            "unknown",
        )

        memory_usage = container.get(
            "memory_usage",
            "unknown",
        )

        memory_percent_raw = container.get(
            "memory_percent_of_limit",
            "0%",
        )

        memory_usage_bytes = parse_memory_usage_bytes(memory_usage)
        total_container_memory_bytes += memory_usage_bytes
        host_memory_share_percent = (
            round(100 * memory_usage_bytes / host_memory_total_bytes, 2)
            if host_memory_total_bytes else None
        )

        container_info = {
            "name": name,
            "memory_usage": memory_usage,
            # This is usage relative to the Docker container's configured
            # limit, not relative to the host. It is displayed as such in UI.
            "memory_percent_of_limit": memory_percent_raw,
            "host_memory_share_percent": host_memory_share_percent,
        }

        container_memory.append(
            container_info
        )

        # ----------------------------------------------------
        # Use absolute usage, not Docker's percentage-of-container-limit.
        # ----------------------------------------------------

        if host_memory_share_percent is not None and (
            host_memory_share_percent >= SIGNIFICANT_HOST_MEMORY_SHARE_PERCENT
        ):

            significant_containers.append(
                {
                    "name": name,
                    "memory_usage": memory_usage,
                    "host_memory_share_percent": host_memory_share_percent,
                }
            )

    # --------------------------------------------------------
    # Significant container utilization
    # --------------------------------------------------------

    if significant_containers:

        total_docker_memory_share_percent = round(
            100 * total_container_memory_bytes / host_memory_total_bytes,
            2,
        ) if host_memory_total_bytes else None

        return {
            "docker_status": "available",
            "running_containers": container_count,
            "docker_container_memory": container_memory,
            "host_memory_usage_percent": host_memory_usage,
            "docker_memory_share_percent": total_docker_memory_share_percent,
            "docker_is_evidently_responsible": "potentially",
            "assessment": "potentially_significant",
            "significant_containers": significant_containers,
            "reason": (
                "One or more Docker containers consume a material share of "
                "the Docker/WSL memory budget at this snapshot. Docker may "
                "be contributing to memory pressure, but this telemetry does "
                "not prove that Docker is the sole cause of host memory use."
            ),
        }

    # --------------------------------------------------------
    # Containers running but low utilization
    # --------------------------------------------------------

    return {
        "docker_status": "available",
        "running_containers": container_count,
        "docker_container_memory": container_memory,
        "host_memory_usage_percent": host_memory_usage,
        "docker_memory_share_percent": round(
            100 * total_container_memory_bytes / host_memory_total_bytes,
            2,
        ) if host_memory_total_bytes else None,
        "docker_is_evidently_responsible": False,
        "assessment": "unlikely",
        "significant_containers": [],
        "reason": (
            "Docker containers are running, but their "
            "absolute memory usage is below five percent of the Docker/WSL "
            "memory budget each. Docker is therefore unlikely to be the "
            "primary cause of the current host memory usage."
        ),
    }


# ============================================================
# RAG CONTEXT
# ============================================================

def get_knowledge(question):
    """
    Retrieve technical knowledge relevant to the user's
    question.
    """

    try:

        documents = retrieve_context(
            question,
            number_of_results=RAG_RESULTS,
        )

        if not documents:
            return []

        return documents

    except Exception as exc:

        print(
            f"RAG retrieval error: {exc}"
        )

        return []


# ============================================================
# PROMPT BUILDER
# ============================================================

def build_prompt(
    question,
    digital_twin,
    diagnosis,
    documents,
    sourcegraph_sources=None,
):
    """
    Build a grounded prompt.

    Telemetry and deterministic diagnosis are explicitly
    authoritative.
    """

    # Keep local CPU inference responsive. Two concise, relevant pieces of
    # knowledge are more useful than a full document dump, especially to Phi-3
    # and TinyLlama.
    documents = (documents or [])[:2]
    context = (
        "\n\n".join(document[:700] for document in documents)
        if documents
        else "No relevant knowledge was retrieved."
    )

    sourcegraph_sources = sourcegraph_sources or []
    repository_evidence = "\n".join(
        f"- {item.get('repository', 'repository')}/"
        f"{item.get('path', 'unknown')}:{item.get('line', '?')} — "
        f"{item.get('preview', '')}"
        for item in sourcegraph_sources[:4]
    ) or "No Sourcegraph repository evidence was available."

    runtime_terms = {
        "container", "cpu", "disk", "docker", "environment", "memory",
        "metric", "monitor", "performance", "resource", "runtime", "telemetry",
    }
    question_terms = {
        word.lower().strip(".,?!") for word in question.split()
    }
    needs_runtime_context = bool(question_terms & runtime_terms)

    if needs_runtime_context:
        docker = digital_twin.get("docker", {})
        containers = docker.get("containers", [])
        # Docker values arrive as display strings (for example "12.4%").
        # Sorting them for the prompt makes the most relevant live evidence
        # visible without forcing a small local model through every container.
        def memory_usage(item):
            return parse_memory_usage_bytes(item.get("memory_usage"))

        telemetry_for_prompt = {
            "system": digital_twin.get("system", {}),
            "docker": {
                "available": docker.get("available", False),
                "container_count": docker.get("container_count", 0),
                "source": docker.get("source"),
                "top_memory_containers": sorted(
                    containers, key=memory_usage, reverse=True
                )[:4],
            },
        }
        diagnosis_for_prompt = {
            key: diagnosis.get(key)
            for key in (
                "docker_status", "running_containers", "host_memory_usage_percent",
                "docker_is_evidently_responsible", "assessment",
                "significant_containers", "reason",
            )
            if key in diagnosis
        }
    else:
        telemetry_for_prompt = {
            "note": "The user asked an architecture/function question; no runtime diagnosis is required."
        }
        diagnosis_for_prompt = {
            "note": "Do not infer runtime causes for an architecture/function question."
        }

    telemetry_json = json.dumps(telemetry_for_prompt, indent=2)
    diagnosis_json = json.dumps(diagnosis_for_prompt, indent=2)

    return f"""
You are DevPulse Nexus.

You are an AI-powered developer environment
observability and AIDevOps intelligence assistant.

Your responsibility is to explain the current
developer environment using:

1. LIVE DIGITAL TWIN TELEMETRY
2. DETERMINISTIC DIAGNOSIS
3. RETRIEVED TECHNICAL KNOWLEDGE

============================================================
CRITICAL RULES
============================================================

The LIVE TELEMETRY is authoritative.

The DETERMINISTIC DIAGNOSIS is authoritative.

The retrieved knowledge is supporting technical context.

You MUST NOT contradict the deterministic diagnosis.

You MUST NOT invent:

- containers
- processes
- memory values
- CPU values
- disk values
- resource limits
- errors
- causes
- configuration
- workloads

If the telemetry does not prove a cause, explicitly say:

"The exact cause cannot be determined from the
available telemetry."

Do not present speculation as fact.

Do not automatically blame Docker for host memory usage.

If running_containers is 0:

Docker containers are NOT responsible for the observed
host memory usage.

If containers are running but their observed memory
utilization is low:

Explain that Docker is unlikely to be the primary cause.

If the deterministic diagnosis says Docker may be
contributing:

Explain that Docker may be contributing, while making
clear that the telemetry does not prove sole causation.

IMPORTANT:

Do not describe ordinary host memory utilization as
a problem unless the telemetry or user question provides
evidence that it is problematic.

Always distinguish:

OBSERVED FACTS

from

LIKELY / POSSIBLE CAUSES.

============================================================
LIVE DIGITAL TWIN
============================================================

{telemetry_json}

============================================================
DETERMINISTIC DIAGNOSIS
============================================================

{diagnosis_json}

============================================================
RETRIEVED TECHNICAL KNOWLEDGE
============================================================

{context}

============================================================
SOURCEGRAPH REPOSITORY EVIDENCE
============================================================

{repository_evidence}

============================================================
USER QUESTION
============================================================

{question}

============================================================
RESPONSE FORMAT
============================================================

Start with a direct answer to the user's question in one or two sentences.

Then use short sections only when they add value:

EVIDENCE:
- Cite relevant telemetry values, RAG knowledge, or Sourcegraph paths.
- Do not mention a source that is not supplied above.

INTERPRETATION:
- Explain what the supplied evidence supports.
- If evidence is insufficient, say exactly what is not established.

NEXT STEP:
- Give one or two practical actions only when useful.

For questions about architecture or a function, explain the function's role
before discussing current telemetry. For diagnostics, distinguish observed
facts from likely causes. Keep the answer concise, specific, and useful.
"""


# ============================================================
# OLLAMA
# ============================================================

def ask_ollama(prompt, model=None):
    """
    Send the grounded prompt to the local Ollama model.

    Returns:

        answer
        latency_seconds
    """

    start = time.perf_counter()

    response = requests.post(
        OLLAMA_URL,

        json={
            "model": model or OLLAMA_MODEL,
            "prompt": prompt,
            "stream": False,

            "options": {
                "num_predict": OLLAMA_NUM_PREDICT
            },
        },

        timeout=OLLAMA_TIMEOUT,
    )

    response.raise_for_status()

    result = response.json()

    latency = round(
        time.perf_counter() - start,
        2,
    )

    answer = result.get(
        "response",
        "",
    ).strip()

    if not answer:

        answer = (
            "The local AI model returned an empty response."
        )

    return answer, latency


# ============================================================
# HOME
# ============================================================

@app.get(
    "/",
    response_class=HTMLResponse,
)
def home(request: Request):

    return templates.TemplateResponse(
        request=request,
        name="index.html",
        context={},
    )


# ============================================================
# HEALTH CHECK
# ============================================================

@app.get("/health")
def health():

    return {
        "status": "ok",
        "service": "DevPulse Nexus",
        "version": "1.0.0",
        "ollama_model": OLLAMA_MODEL,
        "ollama_url": OLLAMA_URL,
    }


@app.get("/models")
def models():
    """Expose models installed in Ollama for the Ask Nexus picker."""
    available = list_available_models()
    return {
        "available": bool(available),
        "default": OLLAMA_MODEL,
        "models": available,
    }


@app.get("/pipeline-status")
def pipeline_status():
    """Live readiness for the telemetry, retrieval, and inference flow."""
    twin = get_digital_twin()
    record_telemetry(twin)
    return {
        "timestamp": twin["timestamp"],
        "telemetry": {
            "available": True,
            "docker": twin.get("docker", {}),
        },
        "rag": {
            "available": True,
            "collection": "devpulse_knowledge",
        },
        "sourcegraph": sourcegraph_status(),
        "models": {
            "available": list_available_models(),
            "default": OLLAMA_MODEL,
        },
    }


# ============================================================
# DIGITAL TWIN API
# ============================================================

@app.get("/digital-twin")
def digital_twin():

    snapshot = get_digital_twin()

    # Every Digital Twin request becomes a history point.
    record_telemetry(snapshot)

    return snapshot


# ============================================================
# TELEMETRY API
# ============================================================

@app.get("/telemetry")
def telemetry():

    return get_system_telemetry()


# ============================================================
# DOCKER API
# ============================================================

@app.get("/docker")
def docker():

    return get_docker_metrics()


# ============================================================
# HISTORY API
# ============================================================

@app.get("/history")
def history(limit: int = 120):
    """
    Return previously recorded Digital Twin snapshots.

    A fresh snapshot is NOT created here.
    This prevents /history from unexpectedly changing
    the telemetry history.
    """

    records = get_history(limit)

    return {
        "count": len(records),
        "records": records,
    }


# ============================================================
# DIAGNOSIS API
# ============================================================

@app.get("/diagnosis")
def diagnosis():

    twin = get_digital_twin()

    result = build_diagnosis(twin)

    return {
        "timestamp": twin["timestamp"],
        "diagnosis": result,
        "digital_twin": twin,
    }


# ============================================================
# ASK API
# ============================================================

@app.get("/ask")
def ask(question: str, model: str | None = None):

    question = question.strip()
    available_models = list_available_models()
    selected_model = model or OLLAMA_MODEL

    if selected_model not in available_models:
        raise HTTPException(
            status_code=400,
            detail=f"Model '{selected_model}' is not currently installed in Ollama.",
        )

    # --------------------------------------------------------
    # Validate question
    # --------------------------------------------------------

    if not question:

        return {
            "question": question,

            "answer": (
                "Please provide a developer or DevOps "
                "question."
            ),

            "diagnosis": None,

            "digital_twin": None,

            "sources": [],

            "ai": {
                "model": selected_model,
                "latency_seconds": None,
                "error": None,
            },
        }

    # --------------------------------------------------------
    # 1. Collect live environment telemetry
    # --------------------------------------------------------

    digital_twin = get_digital_twin()

    # Record the snapshot because /ask is also an
    # observability event.
    record_telemetry(digital_twin)

    # --------------------------------------------------------
    # 2. Produce deterministic diagnosis
    # --------------------------------------------------------

    diagnosis = build_diagnosis(
        digital_twin
    )

    # --------------------------------------------------------
    # 3. Orchestrate application services
    # --------------------------------------------------------

    orchestration = orchestrate_request(
        question=question,
        digital_twin=digital_twin,
        diagnosis=diagnosis,
        rag_results=RAG_RESULTS,
    )

    documents = orchestration["retrieved_context"]
    try:
        repository_sources = search_sourcegraph(question, limit=8)
    except Exception:
        repository_sources = []

    # --------------------------------------------------------
    # 4. Build grounded prompt
    # --------------------------------------------------------

    prompt = build_prompt(
        question=question,
        digital_twin=digital_twin,
        diagnosis=diagnosis,
        documents=documents,
        sourcegraph_sources=repository_sources,
    )

    # --------------------------------------------------------
    # 5. Ask local AI model
    # --------------------------------------------------------

    ai_error = None
    latency = None

    try:

        answer, latency = ask_ollama(
            prompt,
            selected_model,
        )

    except requests.exceptions.Timeout:

        ai_error = (
            "The local AI model timed out. "
            "Live telemetry and deterministic diagnosis "
            "are still available."
        )

        answer = (
            "The local AI model took too long to respond. "
            "Review the returned diagnosis and Digital Twin "
            "telemetry for the current environment state."
        )

    except requests.exceptions.ConnectionError as exc:

        ai_error = (
            "Could not connect to Ollama at "
            f"{OLLAMA_URL}: {exc}"
        )

        answer = (
            "The local AI model is unavailable. "
            "Make sure the Ollama container is running "
                f"and model '{selected_model}' is available."
        )

    except requests.exceptions.HTTPError as exc:

        ai_error = str(exc)

        answer = (
            "Ollama returned an HTTP error while processing "
            "the request. The deterministic diagnosis and "
            "Digital Twin telemetry are still available."
        )

    except requests.exceptions.RequestException as exc:

        ai_error = str(exc)

        answer = (
            "The local AI model could not process the request. "
            "The deterministic diagnosis and Digital Twin "
            "telemetry are still available."
        )

    except Exception as exc:

        ai_error = str(exc)

        print(
            f"Ollama unexpected error: {exc}"
        )

        answer = (
            "An unexpected error occurred while generating "
            "the AI response. The deterministic diagnosis "
            "and Digital Twin telemetry are still available."
        )

    # --------------------------------------------------------
    # 6. Return complete observability response
    # --------------------------------------------------------

    return {
        "question": question,

        "answer": answer,

        "diagnosis": diagnosis,

        "digital_twin": digital_twin,

        "sources": documents,

        "sourcegraph": {
            "status": sourcegraph_status(),
            "results": repository_sources,
        },

        "ai": {
            "model": selected_model,
            "latency_seconds": latency,
            "error": ai_error,
        },
    }



# ============================================================
# WEEK 5 MODEL COMPARISON
# ============================================================

from pydantic import BaseModel as _Week5BaseModel

from app.classifier import classify_question
from app.context import (
    build_context,
    build_combined_prompt,
)
from app.model_runner import (
    OLLAMA_MODELS,
    list_available_models,
    run_all_models,
)
from app.evaluator import evaluate_all
from app.comparison import (
    compare_models,
    load_historical,
)


class CompareRequest(_Week5BaseModel):
    question: str


_comparison_jobs = {}
_comparison_lock = threading.Lock()


def _job_update(job_id, stage, state, message, extra=None):
    event = {
        "timestamp": now_iso(),
        "stage": stage,
        "state": state,
        "message": message,
    }
    if extra:
        event.update(extra)

    with _comparison_lock:
        job = _comparison_jobs.get(job_id)
        if not job:
            return
        job["events"].append(event)
        job["current_stage"] = stage
        job["state"] = state


def _job_result(job_id, result):
    with _comparison_lock:
        job = _comparison_jobs.get(job_id)
        if job:
            job["state"] = "complete"
            job["current_stage"] = "complete"
            job["result"] = result
            job["events"].append({
                "timestamp": now_iso(),
                "stage": "complete",
                "state": "complete",
                "message": "Live comparison completed.",
            })


def _job_error(job_id, message):
    with _comparison_lock:
        job = _comparison_jobs.get(job_id)
        if job:
            job["state"] = "failed"
            job["current_stage"] = "failed"
            job["error"] = message
            job["events"].append({
                "timestamp": now_iso(),
                "stage": "failed",
                "state": "failed",
                "message": message,
            })


def _run_comparison_job(job_id, question):
    """Run the real model evaluation and publish stage changes for the UI."""
    try:
        _job_update(job_id, "telemetry", "running", "Collecting Digital Twin telemetry.")
        twin = get_digital_twin()
        record_telemetry(twin)
        diagnosis = build_diagnosis(twin)
        _job_update(
            job_id,
            "telemetry",
            "complete",
            "Digital Twin and Docker telemetry captured.",
            {"docker_available": twin.get("docker", {}).get("available", False)},
        )

        _job_update(job_id, "retrieval", "running", "Retrieving RAG knowledge and Sourcegraph evidence.")
        context = build_context(question)
        documents = context.get("rag", [])
        sources = context.get("sourcegraph", [])
        sourcegraph = sourcegraph_status()
        evaluation_context = {
            **context,
            "telemetry": twin,
            "diagnosis": diagnosis,
        }
        _job_update(
            job_id,
            "retrieval",
            "complete",
            "RAG retrieval and Sourcegraph search completed.",
            {"rag_documents": len(documents), "sourcegraph_results": len(sources)},
        )

        selected_models = [
            model for model in OLLAMA_MODELS
            if model in list_available_models()
        ]
        if not selected_models:
            raise RuntimeError("No requested comparison models are installed in Ollama.")

        prompt = build_prompt(
            question=question,
            digital_twin=twin,
            diagnosis=diagnosis,
            documents=documents,
            sourcegraph_sources=sources,
        )

        def on_progress(model, state, response):
            message = (
                f"{model} is generating an evidence-grounded answer."
                if state == "running"
                else f"{model} completed."
            )
            _job_update(
                job_id,
                "models",
                "running" if state == "running" else "complete",
                message,
                {"model": model, "model_state": state},
            )

        _job_update(job_id, "models", "running", "Running local models sequentially.")
        responses = run_all_models(prompt, selected_models, on_progress)

        _job_update(job_id, "evaluation", "running", "Scoring live answers against retrieved evidence.")
        category = classify_question(question)
        evaluated = evaluate_all(
            question,
            category,
            responses,
            evaluation_context,
        )
        comparison = compare_models(evaluated, category)
        _job_update(job_id, "evaluation", "complete", "Seven-category scoring and best-model selection completed.")

        _job_result(job_id, {
            "question": question,
            "category": category,
            "models": evaluated,
            "comparison": comparison,
            "telemetry": twin,
            "diagnosis": diagnosis,
            "sourcegraph": {
                "status": sourcegraph,
                "results": sources,
            },
            "rag": {
                "documents": documents,
                "count": len(documents),
            },
        })
    except Exception as exc:
        _job_error(job_id, str(exc))


@app.post("/comparison-jobs")
def create_comparison_job(request: CompareRequest, background_tasks: BackgroundTasks):
    question = request.question.strip()
    if not question:
        raise HTTPException(status_code=400, detail="Question cannot be empty.")

    job_id = uuid.uuid4().hex
    with _comparison_lock:
        _comparison_jobs[job_id] = {
            "id": job_id,
            "question": question,
            "state": "queued",
            "current_stage": "queued",
            "events": [{
                "timestamp": now_iso(),
                "stage": "queued",
                "state": "queued",
                "message": "Comparison queued.",
            }],
            "result": None,
            "error": None,
        }

    background_tasks.add_task(_run_comparison_job, job_id, question)
    return {"id": job_id, "state": "queued"}


@app.get("/comparison-jobs/{job_id}")
def get_comparison_job(job_id: str):
    with _comparison_lock:
        job = _comparison_jobs.get(job_id)
        if not job:
            raise HTTPException(status_code=404, detail="Comparison job not found.")
        return json.loads(json.dumps(job))


@app.get("/evaluation-history")
def evaluation_history():
    return load_historical()


@app.post("/compare")
def compare(request: CompareRequest):
    question = request.question.strip()

    if not question:
        return {
            "error": "Question cannot be empty."
        }

    category = classify_question(question)

    context = build_context(question)

    prompt = build_combined_prompt(
        question,
        context,
    )

    responses = run_all_models(prompt)

    evaluated = evaluate_all(
        question,
        category,
        responses,
        context,
    )

    comparison = compare_models(
        evaluated,
        category,
    )

    return {
        "question": question,
        "category": category,
        "models": evaluated,
        "sourcegraph": {
            "connected": bool(
                context.get("sourcegraph")
            ),
            "query": question,
            "role": (
                "Repository search and evidence retrieval. "
                "Matches are supplied as repository context to the "
                "model and used by the live evaluator for grounding "
                "and unsupported-file checks. Sourcegraph does not "
                "generate or score the answer."
            ),
            "results": context.get(
                "sourcegraph",
                [],
            ),
        },
        "rag": {
            "retrieved": bool(
                context.get("rag")
            ),
            "role": (
                "Knowledge-base retrieval supplied alongside "
                "repository evidence as model context."
            ),
            "sources": context.get(
                "rag",
                [],
            ),
        },
        "comparison": comparison,
        "historical": load_historical(),
    }
